### ISSUE TITLE
Restriction on antismash nodes

### ISSUE THREAD

**Issue by artur-matysik** [socialgene/sgpy#82]
Hi, 

Its more a question about not yet documented `dbmodifiers`, rather than feature request. Maybe I'm doing something wrong, but...

**Is your feature request related to a problem? Please describe.**
Running `socialgene.cli.neo4j.massage --antismash` creates constraint on `(antismash_bgc.nuid, antismash_bgc.region)`, but it seems there is no `nuid` property for `antismash_bgc` node (am I missing something here?). Therefore re-running the command duplicates all the antismash entries. Can this be prevented? How detected antismash region node can be identified? Currently it has only three properties (start, end, region). 

**Describe the solution you'd like**
- Change in constraints? `nuid` definition? 

**Additional context**
- Tested with minimalistic `ultraquickstart` example

**Comment by chasemc** [comment]
Good morning, 

There's two ways to integrate model antismash into the model with pros and cons of each and currently the code needs a very small adjustment so that both aren't performed (happening in this case). I hadn't yet decided on fully implementing both or leaving one. The db modification steps haven't been documented yet because the framework is still being refined so that it's easy to add additional modules by myself or others

Oleg Moskvin from BluMaiden emailed me questions about the project on Dec 21 and I responded Dec 26, with a follow-up on Jan 2, saying I'd be happy to meet and discuss. I haven't received any response and so it's difficult for me to prioritize this request without knowing there will be any two-way communication.

**Comment by chasemc** [comment]
There should be a 0.5.0 version on pypi in the next few minutes 
Two ways to model: either putting antismash BGC info on the [:ENCODES] relationships, or as nodes themselves
Can be done via CLI:

```
 sg_massage --antismash_as_edges 
 ```
 ```
 sg_massage --antismash_as_nodes
```

**Comment by artur-matysik** [comment]
That is perfect, I will test that out once I have a moment. Also curious about other upgrades in the new release! Its a massive project and I have a whole list of questions and thoughts about it. Sorry for delay in contact, I was out of the loop, not aware of the full conversation.
